### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by arolson101** [budiadiono/react-native-calculator#1]
I love this calculator keyboard; thanks for making it!

I'm trying to use the calculator keyboard in a react-native iOS app, and it's all drawing correctly but none of the calculator's text shows up, and the on change events aren't firing either.  I haven't had a chance to investigate further.  Do you know what might be happening?

**Comment by arolson101** [comment]
investigating I find that it's drawing the text transparent because ready is false.  The Display component keeps resizing (inspecting the component the size is constantly increasing).

**Comment by arolson101** [comment]
adding a console.log I see that the size is increasing but nothing else is:

```{complete: false, size: 1125.111111111111, h: 72.5, height: 74.1111111111111, w: 353, …}```

**Comment by budiadiono** [comment]
Hi, thank you for investigating this issue! I'll try to use different approach in handling autosize text in the `Display` component. This time I'll give it a shot with https://facebook.github.io/react-native/docs/text#adjustsfontsizetofit for IOS.

**Comment by budiadiono** [comment]
Oh the `adjustsFontSizeToFit` is only to scale down. Can't use this approach.

**Comment by budiadiono** [comment]
I have no luck with any other approach than `adjustsFontSizeToFit`, so I decided to use it 😐Feel free to send PR if you have any better idea.
