### ISSUE TITLE
textAlign on Calculator component

### ISSUE THREAD

**Issue by WesleyFaveri** [budiadiono/react-native-calculator#2]
Can we have a props to change textAlign of display on calculator component? Missing it.

**Comment by WesleyFaveri** [comment]
I made a pull request, but i cant compile for test it, i got some error from tsc

#3

**Comment by budiadiono** [comment]
Hi thank you for sending the pull request! I think that was good idea -- I've just review your pull request, there's need some fix and changes so I can merge this pull request.

**Comment by WesleyFaveri** [comment]
Done, updated pull request

**Comment by budiadiono** [comment]
Thank you! It's merged now.
