### ISSUE TITLE
Hitting decimal button after Action button NaN.

### ISSUE THREAD

**Issue by MichaelLambs** [budiadiono/react-native-calculator#7]
First off great tool!

using - version: 0.5.0

I wanted to point out that if you hit the decimal button after an action button but before a preceding 0. You will get NaN.

Example:
8 + 0.4 = 8.4 - works correctly.
8 + .4 = 8 + Nan. - returns NaN and requires a clear and restart.

So if you do not hit the 0 prior to a decimal after and action button that error will occur.

I am guessing some users will try and hit the decimal without a preceding 0.

**Comment by budiadiono** [comment]
Solved by #8

**Comment by budiadiono** [comment]
Thank you @MichaelLambs !
