### ISSUE TITLE
Input '--' or '--Number' after empty value got errors warning

### ISSUE THREAD

**Issue by young-cruz** [budiadiono/react-native-calculator#9]
Seems found 2 bugs scenarios with `- -` input
<img width="847" alt="bug 1" src="https://user-images.githubusercontent.com/4417217/52944250-fa19df80-33a9-11e9-88a1-fecdbdd29572.png">
<img width="847" alt="bug 2" src="https://user-images.githubusercontent.com/4417217/52944253-fab27600-33a9-11e9-828d-6ecdffe33e41.png">

**Comment by budiadiono** [comment]
Thank you for reporting this issue @calmrund!
